package JDBC;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.SQLException;
import java.sql.Statement;

public class JDBC_Demo {
    public static void main(String[] args) {
        // Database credentials
        String url = "jdbc:oracle:thin:@localhost:1521:xe"; // Update with your Oracle DB details
        String user = "SYSTEM";  // Use your Oracle username (default is SYSTEM)
        String password = "Universal2024";  // Use your Oracle password

        // Corrected SQL Query for Oracle
        String createTableSQL = "CREATE TABLE JDBC_DEMO ("
                + "id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, "
                + "name VARCHAR2(100) NOT NULL, "
                + "email VARCHAR2(100) UNIQUE NOT NULL, "
                + "age NUMBER NOT NULL"
                + ")";

        // Establishing the connection
        try (Connection conn = DriverManager.getConnection(url, user, password);
             Statement stmt = conn.createStatement()) {

            // Execute the SQL statement
            stmt.executeUpdate(createTableSQL);
            System.out.println("Table 'JDBC_DEMO' created successfully!");

        } catch (SQLException e) {
            e.printStackTrace();
        }
    }
}
